FlowersBack/Models/Flower.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FlowersBack.Models
{
    public class Flower
    {
        [Key]
        public int FlowerId { get; set; }

        [Required(ErrorMessage = "Debes entrar una {0}")]
        [StringLength(30, ErrorMessage = "El campo {0} solo puede contener un maximo de {1} y un minimo de {2} caracteres", MinimumLength = 1)]
        [Index ("Flower_Description_Index",IsUnique =true)]
        public string Description { get; set; }
        [DisplayFormat(DataFormatString ="{0:C2}",ApplyFormatInEditMode =false)]

        [Required(ErrorMessage = "Debes entrar un {0}")]
        public decimal? Price { get; set; }
        //   public decimal? Price { get; set; } con la interrogacion significa que permite null

        //[DataType(DataType.Date)]
        //[DataType(DataType.Date)]
        [DisplayFormat(DataFormatString  = "{0:yyyy/MM/dd}",ApplyFormatInEditMode= false  )]
        public DateTime? LastPurchase { get; set; }

        public string Image { get; set; }


        [Display(Name ="Is active")]
        public bool IsActive { get; set; }

        [DataType(DataType.MultilineText)]
        public string Observation { get; set; }


    }
}

FlowersBack/Models/FlowerView.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Web;

namespace FlowersBack.Models
{
    [NotMapped]
    public class FlowerView : Flower //: flower lo normal seria heredar, pero en este caso particular no: Flower
    {
        
        //public int FlowerId { get; set; }

        //[Required(ErrorMessage = "Debes entrar una {0}")]
        //[StringLength(30, ErrorMessage = "El campo {0} solo puede contener un maximo de {1} y un minimo de {2} caracteres", MinimumLength = 1)]
        
        //public string Description { get; set; }
        //[DisplayFormat(DataFormatString = "{0:C2}", ApplyFormatInEditMode = false)]

        //[Required(ErrorMessage = "Debes entrar un {0}")]
        //public decimal? Price { get; set; }
        ////   public decimal? Price { get; set; } con la interrogacion significa que permite null

        ////[DataType(DataType.Date)]
        //[Display(Name = "Last purchase")]
        //public DateTime? LastPurchase { get; set; }
        [Display(Name = "Image")]
        public HttpPostedFileBase ImageFile { get; set; }
        //public string Image { get; set; }


        //[Display(Name = "Is active")]
        //public bool IsActive { get; set; }

        //[DataType(DataType.MultilineText)]
        //public string Observation { get; set; }

       
    }
}

FlowersBack/Controllers/API/FlowersController.cs
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Web.Http;
using System.Web.Http.Description;
using FlowersBack.Models;

namespace FlowersBack.Controllers.API
{
    public class FlowersController : ApiController
    {
        private DataContext db = new DataContext();

        // GET: api/Flowers
        public IQueryable<Flower> GetFlowers()
        {
            return db.Flowers;
        }

        // GET: api/Flowers/5
        [ResponseType(typeof(Flower))]
        public IHttpActionResult GetFlower(int id)
        {
            Flower flower = db.Flowers.Find(id);
            if (flower == null)
            {
                return NotFound();
            }

            return Ok(flower);
        }

        // PUT: api/Flowers/5
        [ResponseType(typeof(void))]
        public IHttpActionResult PutFlower(int id, Flower flower)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            if (id != flower.FlowerId)
            {
                return BadRequest();
            }

            db.Entry(flower).State = EntityState.Modified;

            try
            {
                db.SaveChanges();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!FlowerExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return StatusCode(HttpStatusCode.NoContent);
        }

        // POST: api/Flowers
        [ResponseType(typeof(Flower))]
        public IHttpActionResult PostFlower(Flower flower)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            db.Flowers.Add(flower);
            db.SaveChanges();

            return CreatedAtRoute("DefaultApi", new { id = flower.FlowerId }, flower);
        }

        // DELETE: api/Flowers/5
        [ResponseType(typeof(Flower))]
        public IHttpActionResult DeleteFlower(int id)
        {
            Flower flower = db.Flowers.Find(id);
            if (flower == null)
            {
                return NotFound();
            }

            db.Flowers.Remove(flower);
            db.SaveChanges();

            return Ok(flower);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private bool FlowerExists(int id)
        {
            return db.Flowers.Count(e => e.FlowerId == id) > 0;
        }
    }
}

FlowersBack/Controllers/FlowersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FlowersBack.Models;
using FlowersBack.Classes;

namespace FlowersBack.Controllers
{
    public class FlowersController : Controller
    {
        private DataContext db;

        public FlowersController()
        {
            db = new DataContext();
        }

        // GET: Flowers
        public ActionResult Index()
        {
            return View(db.Flowers.OrderBy(f=> f.Description).ToList());
        }

        // GET: Flowers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var flower = db.Flowers.Find(id);

            if (flower == null)
            {
                return HttpNotFound();
            }

            return View(flower);
        }

        // GET: Flowers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Flowers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "FlowerId,Description,Price,LastPurchase,Image,IsActive,Observation")] Flower flower)
        public ActionResult Create(FlowerView view)
        {
            if (ModelState.IsValid)
            {
                var pic = string.Empty;
                var folder = "~/Content/Images";

                if (view.ImageFile != null)
                {
                    pic = FilesHelper.UploadPhoto(view.ImageFile, folder);
                    pic = string.Format("{0}/{1}", folder, pic);
                }
                var flower = ToFlower(view);
                flower.Image = pic;
                //db.Flowers.Add(flower);
                db.Flowers.Add(flower);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(view);
           // return View(flower);
        }

        private Flower ToFlower(FlowerView view)
        {
            return new Models.Flower
            {
                Description = view.Description,
                FlowerId = view.FlowerId,
                Image = view.Image,
                IsActive = view.IsActive,
                LastPurchase = view.LastPurchase,
                Observation = view.Observation,
                Price = view.Price,
            };
        }

        // GET: Flowers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //Flower flower = db.Flowers.Find(id);
            var flower = db.Flowers.Find(id);

            if (flower == null)
            {
                return HttpNotFound();
            }

            //return View(flower);
            return View(ToView(flower));
        }

        private FlowerView ToView(Flower flower)
        {
            return new FlowerView
            {
                Description = flower.Description,
                FlowerId = flower.FlowerId,
                Image = flower.Image,
                IsActive = flower.IsActive,
                LastPurchase = flower.LastPurchase,
                Observation = flower.Observation,
                Price = flower.Price,
            };
        }

        // POST: Flowers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
     //   public ActionResult Edit([Bind(Include = "FlowerId,Description,Price,LastPurchase,Image,IsActive,Observation")] Flower flower)
      [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit( FlowerView view)
        {
            if (ModelState.IsValid)
            {
                var pic = view.Image; //la inicializo en la imagen vieja por si el no la cambio no la dañe
                var folder = "~/Content/Images";

                if (view.ImageFile != null)
                {
                    pic = FilesHelper.UploadPhoto(view.ImageFile, folder);
                    pic = string.Format("{0}/{1}", folder, pic);
                }

                var flower = ToFlower(view); //convertimos a vista
                flower.Image = pic;
                db.Entry(flower).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(view);
        }

        // GET: Flowers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Flower flower = db.Flowers.Find(id);
            if (flower == null)
            {
                return HttpNotFound();
            }
            return View(flower);
        }

        // POST: Flowers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Flower flower = db.Flowers.Find(id);
            db.Flowers.Remove(flower);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FlowersBack/Views/Flowers/Create.cshtml
@model FlowersBack.Models.FlowerView

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Flowers", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Flower</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.LastPurchase, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class='input-group date' id='datepicker' style="width:280px">
                    @Html.EditorFor(model => model.LastPurchase, new { htmlAttributes = new { @class = "form-control" } })
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
                @Html.ValidationMessageFor(model => model.LastPurchase, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.LastPurchase, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.LastPurchase, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.LastPurchase, "", new { @class = "text-danger" })
                </div>
            </div>*@
        <div class="form-group">
            @Html.LabelFor(model => model.ImageFile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="file-input-new">
                    <div class="input-group" style="width:280px">
                        <div tabindex="500" class="form-control file-caption">
                            <div class="file-caption-name" id="NombreArchivo">
                            </div>
                        </div>
                        <div class="input-group-btn" style="height:auto">
                            <div tabindex="500" class="btn btn-primary btn-file">
                                <i class="glyphicon glyphicon-folder-open"></i>
                                File Search...
                                @Html.TextBoxFor(modelo => modelo.ImageFile, new { type = "file", id = "files" })
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.ImageFile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <span class="btn btn-default btn-file">
                    @Html.TextBoxFor(modelo => modelo.ImageFile, new { type = "file" })
                </span>
            </div>
        </div>*@

        @*<div class="form-group">
                @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Image, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsActive)
                    @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Observation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Observation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Observation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $(function () {
            $('#datepicker').datetimepicker({ format: 'YYYY/MM/DD' });
        });
    </script>

}

FlowersBack/Views/Flowers/Delete.cshtml
@model FlowersBack.Models.Flower

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Flower</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastPurchase)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastPurchase)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)

        </dt>

        <dd>
            @if (!string.IsNullOrEmpty(Model.Image))
            {
                <img src="@Url.Content(Model.Image)" alt="Image" style="width:250px;height:250px;max-width: 100%; height: auto;" />
            }
            @*@Html.DisplayFor(model => model.Image)*@
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Observation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Observation)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

FlowersBack/Views/Flowers/Details.cshtml
@model FlowersBack.Models.Flower

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Flower</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastPurchase)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastPurchase)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
           
        </dt>

        <dd>
            @*@Html.DisplayFor(model => model.Image)*@
            @if (!string.IsNullOrEmpty(Model.Image))
            {
                <img src="@Url.Content(Model.Image)" alt="Image" style="width:300px;height:300px;max-width: 100%; height: auto;" />
            }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Observation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Observation)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.FlowerId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

FlowersBack/Views/Flowers/Edit.cshtml
@*@model FlowersBack.Models.Flower*@
@model FlowersBack.Models.FlowerView
@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@*@using (Html.BeginForm())*@

@using (Html.BeginForm("Edit", "Flowers", FormMethod.Post, new { enctype = "multipart/form-data" }))

{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Flower</h4>
        <hr />
        @if (!string.IsNullOrEmpty(Model.Image))
        {
            <img src="@Url.Content(Model.Image)" alt="Image" style="width:300px;height:300px;max-width: 100%; height: auto;" />
        }
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.FlowerId)
        @Html.HiddenFor(model => model.Image)
         @*//para evitar que llegue nula la imagen que tenia el usuario previamente*@




        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.LastPurchase, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class='input-group date' id='datepicker' style="width:280px">
                    @Html.EditorFor(model => model.LastPurchase, new { htmlAttributes = new { @class = "form-control" } })
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
                @Html.ValidationMessageFor(model => model.LastPurchase, "", new { @class = "text-danger" })
            </div>
        </div>
        @*<div class="form-group">
            @Html.LabelFor(model => model.LastPurchase, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastPurchase, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastPurchase, "", new { @class = "text-danger" })
            </div>
        </div>*@
        <div class="form-group">
            @Html.LabelFor(model => model.ImageFile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="file-input-new">
                    <div class="input-group" style="width:280px">
                        <div tabindex="500" class="form-control file-caption">
                            <div class="file-caption-name" id="NombreArchivo">
                            </div>
                        </div>
                        <div class="input-group-btn" style="height:auto">
                            <div tabindex="500" class="btn btn-primary btn-file">
                                <i class="glyphicon glyphicon-folder-open"></i>
                                File Search...
                                @Html.TextBoxFor(modelo => modelo.ImageFile, new { type = "file", id = "files" })
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        @*<div class="form-group">
            @Html.LabelFor(model => model.ImageFile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <span class="btn btn-default btn-file">
                    @Html.TextBoxFor(modelo => modelo.ImageFile, new { type = "file" })
                </span>
            </div>
        </div>*@
        @*<div class="form-group">
                @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Image, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsActive)
                    @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Observation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Observation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Observation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
<script type="text/javascript">
        $(function () {
            $('#datepicker').datetimepicker({ format: 'YYYY/MM/DD' });
        });
</script>
}

FlowersBack/Views/Flowers/Index.cshtml
@model IEnumerable<FlowersBack.Models.Flower>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p> @*Nombre, Accion a ejecutar en el controlardo, parametros (los mando vacios), estilos o elementos html*@
    @*@Html.ActionLink("Create New", "Create", new { }, new { @class = "btn btn-primary" })*@

   <a class="btn btn-primary" href="/Flowers/Create"> Create New <span class="glyphicon glyphicon-plus"></span> </a>
</p>
<table class="table table-striped table-bordered table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastPurchase)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Image)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsActive)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.Observation)
        </th>*@
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastPurchase)
            </td>
            <td>
                @if (!string.IsNullOrEmpty(item.Image))
                {
                    <img src="@Url.Content(item.Image)" alt="Image" style="width:100px;height:100px;max-width: 100%; height: auto;" />
                }

                @*@Html.DisplayFor(modelItem => item.Image)*@
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsActive)
            </td>
            @*<td>
                @Html.DisplayFor(modelItem => item.Observation)
            </td>*@
            <td>
                <a class="btn btn-warning" href="/Flowers/Edit/@item.FlowerId"> Edit <span class="glyphicon glyphicon-edit"></span> </a>
                <a class="btn btn-info" href="/Flowers/Details/@item.FlowerId"> Details <span class="glyphicon glyphicon-exclamation-sign"></span> </a>
                <a class="btn btn-danger" href="/Flowers/Delete/@item.FlowerId"> Delete <span class="glyphicon glyphicon-trash"></span> </a>
                @*@Html.ActionLink("Edit", "Edit", new { id = item.FlowerId }, new { @class = "btn btn-warning" }) 
                @Html.ActionLink("Details", "Details", new { id = item.FlowerId }, new { @class = "btn btn-info" }) 
                @Html.ActionLink("Delete", "Delete", new { id = item.FlowerId }, new { @class = "btn btn-danger" })*@
            </td>
        </tr>
    }

</table>